### ISSUE TITLE
React.createElement invalid type when clicking Action Button inside of modal

### ISSUE THREAD

**Issue by tejasmanohar** [maxchehab/phelia#24]
I've been running into an issue with handling onClick inside of a modal. Reproducible simple example-- https://gist.github.com/tejasmanohar/a558884cb2dbca648c872c53c241e56f

Whenever I click it, I see a call to my "interactive" Slack endpoint and following error in my logs

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at createFiberFromTypeAndProps (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:15378:21)
    at createFiberFromElement (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:15401:15)
    at reconcileSingleElement (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:5003:23)
    at reconcileChildFibers (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:5063:35)
    at reconcileChildren (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:7573:28)
    at updateHostRoot (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:8062:5)
    at beginWork (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:9428:14)
    at Object.invokeGuardedCallbackImpl (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:10557:10)
    at invokeGuardedCallback (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:10733:31)
    at beginWork$1 (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:14616:7)
    at performUnitOfWork (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:13570:12)
    at workLoopSync (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:13543:22)
    at performSyncWorkOnRoot (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:13141:9)
    at /Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:1802:24
    at unstable_runWithPriority (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/scheduler/cjs/scheduler.development.js:653:12)
    at runWithPriority (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:1752:10)
    at flushSyncCallbackQueueImpl (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:1797:7)
    at flushSyncCallbackQueue (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:1785:3)
    at scheduleUpdateOnFiber (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:12584:9)
    at Object.updateContainer (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/react-reconciler/cjs/react-reconciler.development.js:15851:3)
    at reconcile (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/phelia/dist/core/reconciler.js:234:24)
    at Object.<anonymous> (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/phelia/dist/core/reconciler.js:240:36)
    at Generator.next (<anonymous>)
    at /Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/phelia/dist/core/reconciler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/phelia/dist/core/reconciler.js:4:12)
    at Object.render (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/phelia/dist/core/reconciler.js:239:12)
    at Phelia.<anonymous> (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/phelia/dist/core/phelia.js:316:36)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/tejasmanohar/dev/src/github.com/carrytravel/hightouch-api/node_modules/phelia/dist/core/phelia.js:5:58)
```

**Comment by chrissysemens** [comment]
I'm also getting this. Did you find a work around @tejasmanohar?

![image](https://user-images.githubusercontent.com/46443589/83779763-457dfd00-a684-11ea-8deb-657c0021ba5f.png)

**Comment by royletron** [comment]
@chrissysemens and @tejasmanohar I was struggling with the same issue. I found it was because I didn't have the parent as a registered component. So the modal I wanted to open was there, but the message (in my case it was a message) wasn't, so it was unable to resolve the `onClick`.

**Comment by tejasmanohar** [comment]
Yeah this was because I didn't have the parent as a registered component
